[package]
name = "markovpass"
version = "1.0.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
rand = "0.3.0"

[[bin]]
path = "src/main.rs"
name = "markovpass"
