name: Build
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-gnu, linux-musl, macos, windows]
        arch: [x86_64, aarch64]
        exclude:
          - build: windows
            arch: aarch64
        include:
          - build: linux-gnu
            os: ubuntu-latest
            target-os: unknown-linux-gnu
            rust: stable
          - build: linux-musl
            os: ubuntu-latest
            target-os: unknown-linux-musl
            rust: stable
          - build: macos
            os: macos-latest
            target-os: apple-darwin
            rust: stable
          - build: windows
            os: windows-latest
            target-os: pc-windows-msvc
          - build: windows
            target-os: pc-windows-msvc
            arch: x86_64
            rust: stable-x86_64-msvc
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        target: ${{ matrix.arch }}-${{ matrix.target-os }}

    - name: Build binary
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.arch }}-${{ matrix.target-os }}

    - name: Build archive
      id: build_archive
      shell: bash
      run: |
        version="$(cargo metadata --format-version 1 | jq -r '[.packages[]|select(.name=="markovpass")][0].version')"
        mkdir archive
        cp LICENSE README.md archive/
        cd archive
        if [ "${{ matrix.build }}" = "windows" ]; then
          cp "../target/${{ matrix.arch }}-${{ matrix.target-os }}/release/markovpass.exe" ./
          name="markovpass-$version-${{ matrix.arch }}-${{ matrix.target-os }}.7z"
          7z a "$name" LICENSE README.md markovpass.exe
        else
          cp "../target/${{ matrix.arch }}-${{ matrix.target-os }}/release/markovpass" ./
          name="markovpass-$version-${{ matrix.arch }}-${{ matrix.target-os }}.tar.gz"
          tar -czf "$name" LICENSE README.md markovpass
        fi
        echo "::set-output name=name::$name"

    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.build_archive.outputs.name }}
        path: archive/${{ steps.build_archive.outputs.name }}
  make_deb:
    name: Make .deb
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build .deb
      id: deb
      run: |
        cargo install cargo-deb
        deb_file=$(cargo deb)
        echo "::set-output name=name::$(basename $deb_file)"

    - name: Upload .deb
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.deb.outputs.name }}
        path: target/debian/${{ steps.deb.outputs.name }}
