name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-gnu, linux-musl, macos, windows]
        arch: [x86_64, aarch64]
        exclude:
          - build: windows
            arch: aarch64
        include:
          - build: linux-gnu
            os: ubuntu-latest
            target-os: unknown-linux-gnu
            rust: stable
            command: cross
          - build: linux-musl
            os: ubuntu-latest
            target-os: unknown-linux-musl
            rust: stable
            command: cross
          - build: macos
            os: macos-latest
            target-os: apple-darwin
            rust: stable
            command: cargo
          - build: windows
            os: windows-latest
            target-os: pc-windows-msvc
          - build: windows
            target-os: pc-windows-msvc
            arch: x86_64
            rust: stable-x86_64-msvc
            command: cargo
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ matrix.arch }}-${{ matrix.target-os }}

    - name: Install Cross
      if: matrix.command == 'cross'
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build binary
      run: ${{ matrix.command }} build --release --verbose --target ${{ matrix.arch }}-${{ matrix.target-os }}
      env:
        RUST_BACKTRACE: 1

    - name: Build archive
      id: build_archive
      shell: bash
      run: |
        version="$(cargo metadata --format-version 1 | jq -r '[.packages[]|select(.name=="markovpass")][0].version')"
        mkdir archive
        cp LICENSE README.md archive/
        cd archive
        if [ "${{ matrix.build }}" = "windows" ]; then
          cp "../target/${{ matrix.arch }}-${{ matrix.target-os }}/release/markovpass.exe" ./
          name="markovpass-$version-${{ matrix.arch }}-${{ matrix.target-os }}.7z"
          7z a "$name" *
        else
          cp "../target/${{ matrix.arch }}-${{ matrix.target-os }}/release/markovpass" ./
          name="markovpass-$version-${{ matrix.arch }}-${{ matrix.target-os }}.tar.gz"
          tar -czf "$name" *
        fi
        echo "name=$name" >> "$GITHUB_OUTPUT"

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build_archive.outputs.name }}
        path: archive/${{ steps.build_archive.outputs.name }}

  make_deb:
    name: Make .deb
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly

    - name: Build .deb
      id: deb
      run: |
        cargo install cargo-deb
        debfile=$(cargo deb)
        result=$?
        echo "debfile=$(basename $debfile)" >> "$GITHUB_OUTPUT"
        exit $result

    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.deb.outputs.debfile }}
        path: target/debian/${{ steps.deb.outputs.debfile }}

  release:
    name: Create release
    needs: [build, make_deb]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        draft: true
        files: |
          artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
